#!/bin/sh
# @version $Id: revoke 911 2018-10-31 21:51:24Z anrdaemon $

# $0 cert <path>

test "$( basename "$0" )" = "minica.sh" || {
    "$( dirname "$( readlink -e "$0" )" )/minica.sh" "$( basename "$0" )" "$@"
    exit $?
  }

test "$MCA_CERT" || {
  echo "mca: No certificate specified, aborting."
  exit 2
}

openssl x509 -subject -serial -dates -noout -nameopt utf8,sep_multiline,lname,use_quote,align < "$MCA_CERT" | sed -re "s/subject=/Revoking certificate for:/" || exit 1

openssl ca -revoke "$MCA_CERT"
